projects:
  cdk-bookmark-appsync-api:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-east-2
        apiId: o2moxrflknhkjci3ruro3hl5y4
        maxDepth: 2
extensions:
  amplify:
    version: 3
